# Generated by Django 3.1.6 on 2021-08-29 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MailingCredential',
        ),
    ]
