# Generated by Django 3.1.6 on 2021-08-14 02:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(help_text="Provider's Brand", max_length=100, null=True, verbose_name='Company')),
                ('address', models.CharField(blank=True, help_text="Company's Address", max_length=250, null=True, verbose_name='Address')),
                ('email', models.EmailField(blank=True, help_text="Company's Email", max_length=254, null=True, verbose_name='Email')),
                ('contact', models.CharField(blank=True, help_text='Providers Contact', max_length=100, null=True, verbose_name='Phone Number')),
                ('provider_type', models.CharField(blank=True, choices=[('LP', 'Laboratory'), ('MP', 'Medical Provider')], help_text="Provider's Type", max_length=100, null=True, verbose_name='Type')),
                ('created_by', models.ForeignKey(blank=True, help_text='provider', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Provider',
                'verbose_name_plural': 'Providers',
                'unique_together': {('company', 'created_by')},
            },
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Visitor's First Name", max_length=100, null=True, verbose_name="Visitor's Name")),
                ('last_name', models.CharField(help_text="Visitor's Last Name", max_length=100, null=True, verbose_name="Visitor's Last Name")),
                ('contact', models.CharField(blank=True, help_text="Visitor's Contact", max_length=100, null=True, verbose_name='Phone Number')),
                ('email', models.EmailField(blank=True, help_text="Visitor's Email", max_length=254, null=True, verbose_name='Email')),
                ('company', models.ForeignKey(help_text='Providers Brand', null=True, on_delete=django.db.models.deletion.CASCADE, to='providers.provider')),
                ('created_by', models.ForeignKey(blank=True, help_text='Created By', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visitor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Visitor',
                'verbose_name_plural': 'Visitors',
            },
        ),
    ]
