# Generated by Django 3.1.6 on 2021-08-14 02:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseConsult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(help_text='Date the consult will be done', null=True, verbose_name='Date & Time')),
                ('motive', models.TextField(help_text='The motive of your assistance to the consult', null=True, verbose_name='Motive')),
                ('suffering', models.TextField(help_text='What is the patient suffering?', null=True, verbose_name='Suffering')),
                ('charge', models.DecimalField(decimal_places=2, help_text='Charge Amount', max_digits=10, null=True, verbose_name='Charges')),
                ('icd_10_detail', models.TextField(blank=True, help_text='ICD-10 Diagnose Details', null=True, verbose_name='ICD-10 Detail')),
                ('diagnose', models.TextField(blank=True, help_text='Diagnose', null=True, verbose_name='Diagnose')),
                ('procedure', models.TextField(blank=True, help_text='Procedure', null=True, verbose_name='Procedure')),
                ('analysis', models.TextField(blank=True, help_text='Analysis', null=True, verbose_name='Analysis')),
                ('notes', models.TextField(blank=True, help_text='Notes', null=True, verbose_name='Notes')),
                ('indications', models.TextField(blank=True, help_text='Indications', null=True, verbose_name='Indications')),
                ('actions', models.TextField(blank=True, help_text='Actions', null=True, verbose_name='Actions')),
                ('prescription', models.FileField(blank=True, help_text='Prescription', null=True, upload_to='appointments/prescriptions', verbose_name='Prescription')),
                ('instructions', models.CharField(blank=True, help_text='Instructions', max_length=512, null=True, verbose_name='Instructions')),
                ('medical_status', models.BooleanField(blank=True, default=False, help_text='Handles the medical consult status', null=True, verbose_name='Medical Status')),
                ('status', models.CharField(blank=True, choices=[('OPEN', 'Open'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('CLOSED', 'Closed')], default='OPEN', help_text='Handles the consult status', max_length=10, null=True, verbose_name='Status')),
                ('lock', models.BooleanField(default=True, help_text='Consult lock status', null=True, verbose_name='Lock')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Consult',
                'verbose_name_plural': 'Consults',
                'ordering': ('datetime',),
            },
        ),
        migrations.CreateModel(
            name='Icd10Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Icd-10 Code', max_length=50, null=True, verbose_name='code')),
            ],
            options={
                'verbose_name': 'ICD-10 Group',
                'verbose_name_plural': 'ICD-10 Groups',
            },
        ),
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Vaccine name', max_length=100, null=True, verbose_name='Name')),
                ('scientific_name', models.CharField(blank=True, help_text="Vaccine's scientific name", max_length=100, null=True, verbose_name='Scientific Name')),
                ('purpose', models.TextField(help_text="Vaccine's purpose", null=True, verbose_name='Purpose')),
                ('laboratory', models.CharField(blank=True, help_text='Laboratory', max_length=100, null=True, verbose_name='Laboratory')),
                ('comments', models.TextField(blank=True, help_text='Comments about the vaccine', null=True, verbose_name='Comments')),
                ('created_by', models.ForeignKey(blank=True, help_text='Created_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vaccine', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Vaccine',
                'verbose_name_plural': 'Vaccines',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='AllergyAndImmunologicalConsult',
            fields=[
                ('baseconsult_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='appointments.baseconsult')),
                ('general_notes', models.TextField(blank=True, help_text='Consult General Notes', null=True, verbose_name='General Notes')),
            ],
            options={
                'verbose_name': 'Allergy and Immunological Consult',
                'verbose_name_plural': 'Allergy and Immunological Consults',
            },
            bases=('appointments.baseconsult',),
        ),
        migrations.CreateModel(
            name='DentalConsult',
            fields=[
                ('baseconsult_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='appointments.baseconsult')),
                ('general_notes', models.TextField(blank=True, help_text='Consult General Notes', null=True, verbose_name='General Notes')),
            ],
            options={
                'verbose_name': 'Dental Consult',
                'verbose_name_plural': 'Dental Consults',
            },
            bases=('appointments.baseconsult',),
        ),
        migrations.CreateModel(
            name='GeneralConsult',
            fields=[
                ('baseconsult_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='appointments.baseconsult')),
                ('blood_pressure', models.CharField(blank=True, help_text='Blood Pressure', max_length=10, null=True, verbose_name='Blood Pressure')),
                ('temperature', models.FloatField(blank=True, help_text='Corporal Temperature', null=True, verbose_name='Temperature')),
                ('weight', models.FloatField(blank=True, help_text='Weight', null=True, verbose_name='Weight')),
                ('size', models.FloatField(blank=True, help_text='Size', null=True, verbose_name='Height')),
                ('digestive_system', models.TextField(blank=True, help_text='Digestive System Analysis', null=True, verbose_name='Digestive System')),
                ('endocrine_system', models.TextField(blank=True, help_text='Endocrine System Analysis', null=True, verbose_name='Endocrine System')),
                ('renal_system', models.TextField(blank=True, help_text='Renal System Analysis', null=True, verbose_name='Renal System')),
                ('lymphatic_system', models.TextField(blank=True, help_text='Lymphatic System Analysis', null=True, verbose_name='Lymphatic System')),
                ('respiratory_system', models.TextField(blank=True, help_text='Respiratory System Analysis', null=True, verbose_name='Respiratory System')),
                ('head_exploration', models.TextField(blank=True, help_text='Head Exploration Analysis', null=True, verbose_name='Head Exploration')),
                ('thorax_exploration', models.TextField(blank=True, help_text='Thorax Exploration Analysis', null=True, verbose_name='Thorax Exploration')),
            ],
            options={
                'verbose_name': 'General Consult',
                'verbose_name_plural': 'General Consults',
            },
            bases=('appointments.baseconsult',),
        ),
        migrations.CreateModel(
            name='GynecologicalConsult',
            fields=[
                ('baseconsult_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='appointments.baseconsult')),
                ('general_notes', models.TextField(blank=True, help_text='Consult General Notes', null=True, verbose_name='General Notes')),
            ],
            options={
                'verbose_name': 'Gynecological Consult',
                'verbose_name_plural': 'Gynecological Consults',
            },
            bases=('appointments.baseconsult',),
        ),
        migrations.CreateModel(
            name='NeurologicalConsult',
            fields=[
                ('baseconsult_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='appointments.baseconsult')),
                ('general_notes', models.TextField(blank=True, help_text='Consult General Notes', null=True, verbose_name='General Notes')),
            ],
            options={
                'verbose_name': 'Neurological Consult',
                'verbose_name_plural': 'Neurological Consults',
            },
            bases=('appointments.baseconsult',),
        ),
        migrations.CreateModel(
            name='OphthalmologyConsult',
            fields=[
                ('baseconsult_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='appointments.baseconsult')),
                ('general_notes', models.TextField(blank=True, help_text='Consult General Notes', null=True, verbose_name='General Notes')),
            ],
            options={
                'verbose_name': 'Ophthalmology Consult',
                'verbose_name_plural': 'Ophthalmology Consults',
            },
            bases=('appointments.baseconsult',),
        ),
        migrations.CreateModel(
            name='PsychiatryConsult',
            fields=[
                ('baseconsult_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='appointments.baseconsult')),
                ('general_notes', models.TextField(blank=True, help_text='Consult General Notes', null=True, verbose_name='General Notes')),
            ],
            options={
                'verbose_name': 'Psychiatry Consult',
                'verbose_name_plural': 'Psychiatry Consults',
            },
            bases=('appointments.baseconsult',),
        ),
        migrations.CreateModel(
            name='SurgicalConsult',
            fields=[
                ('baseconsult_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='appointments.baseconsult')),
                ('general_notes', models.TextField(blank=True, help_text='Consult General Notes', null=True, verbose_name='General Notes')),
            ],
            options={
                'verbose_name': 'Surgical Consult',
                'verbose_name_plural': 'Surgical Consults',
            },
            bases=('appointments.baseconsult',),
        ),
        migrations.CreateModel(
            name='UrologicalConsult',
            fields=[
                ('baseconsult_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='appointments.baseconsult')),
                ('general_notes', models.TextField(blank=True, help_text='Consult General Notes', null=True, verbose_name='General Notes')),
            ],
            options={
                'verbose_name': 'Urological Consult',
                'verbose_name_plural': 'Urological Consults',
            },
            bases=('appointments.baseconsult',),
        ),
        migrations.CreateModel(
            name='VaccineApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(help_text='Surgery date and time', null=True, verbose_name='Datetime')),
                ('comments', models.TextField(blank=True, help_text='Surgery comments or important notes', null=True, verbose_name='Comments')),
                ('patient', models.ForeignKey(blank=True, help_text='Patient receiving the surgery', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vaccine', to='patients.patient')),
                ('vaccine_applied', models.ForeignKey(help_text='Vaccine Applied', null=True, on_delete=django.db.models.deletion.CASCADE, to='appointments.vaccine', verbose_name='Vaccine')),
            ],
            options={
                'verbose_name': 'Vaccine applied',
                'verbose_name_plural': 'Vaccines applied',
                'ordering': ('-datetime',),
            },
        ),
        migrations.CreateModel(
            name='Surgery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(help_text='Surgery date and time', null=True, verbose_name='Datetime')),
                ('surgery_type', models.CharField(choices=[('BAS', 'Bariatric Surgery'), ('BRS', 'Breast Surgery'), ('CRS', 'Colon and Rectal Surgery'), ('ES', 'Endocrine Surgery'), ('GS', 'General Surgery'), ('GYS', 'Gynecological Surgery'), ('HS', 'Hand Surgery'), ('HRS', 'Hernia Surgery'), ('NEUS', 'Neurological Surgery'), ('ORTS', 'Orthopedic Surgery'), ('OPHS', 'Ophthalmological Surgery'), ('OUTS', 'Outpatient Surgery'), ('PS', 'Pediatric Surgery'), ('PRS', 'Plastic and Reconstructive Surgery'), ('RS', 'Robotic Surgery'), ('THS', 'Thoracic Surgery'), ('TRS', 'Trauma Surgery'), ('US', 'Urological Surgery'), ('VS', 'Vascular Surgery'), ('MIS', 'Minimally Invasive Surgery')], help_text='Surgery Type', max_length=50, null=True, verbose_name='Type')),
                ('about', models.TextField(blank=True, help_text='Information about the surgery', null=True, verbose_name='About')),
                ('comments', models.TextField(blank=True, help_text='Surgery comments or important notes', null=True, verbose_name='Comments')),
                ('status', models.CharField(blank=True, choices=[('OPEN', 'Open'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('CLOSED', 'Closed')], default='OPEN', help_text='Surgery status', max_length=10, null=True, verbose_name='Status')),
                ('medical_status', models.BooleanField(blank=True, default=False, help_text='Medical Surgery Status', null=True, verbose_name='Medical Status')),
                ('patient', models.ForeignKey(blank=True, help_text='Patient receiving the surgery', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='surgery', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Surgery',
                'verbose_name_plural': 'Surgeries',
                'ordering': ('datetime',),
            },
        ),
        migrations.CreateModel(
            name='MedicalTestResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, help_text='Date the exams were presented', null=True, verbose_name='date')),
                ('type', models.CharField(choices=[('', '----------'), ('AMN', 'Amniocentesis'), ('BA', 'Blood Analysis'), ('GFA', 'Gastric Fluid Analysis'), ('KFT', 'Kidney Function Test'), ('LFT', 'Liver Function Test'), ('LP', 'Lumbar Puncture'), ('MT', 'Malabsorption Test'), ('PS', 'PAP Smear'), ('PHT', 'Phenolsulfonphthalein Test'), ('PGT', 'Pregnancy Test'), ('PNT', 'Prenatal Test'), ('PBIO', 'Protein-Bound Iodine Test'), ('SYPT', 'Syphilis Test'), ('THOR', 'Thoracentesis'), ('TFT', 'Thyroid Function Test'), ('TXT', 'Toxicology Test'), ('UR', 'Urinalysis/Uroscopy'), ('DI', 'Diagnostic Imaging'), ('GT', 'Genetic Testing'), ('M', 'Measurement'), ('PAVE', 'Physical and Visual Examination')], help_text='Type of exams', max_length=100, null=True, verbose_name='type of exams')),
                ('image', models.ImageField(blank=True, help_text='Exam IMG', null=True, upload_to='appointments/exams', verbose_name='exam')),
                ('consult', models.ForeignKey(blank=True, help_text='Medical Exams', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam', to='appointments.baseconsult', verbose_name='Consult')),
            ],
            options={
                'verbose_name': 'Medical Test Result',
                'verbose_name_plural': 'Medical Test Results',
            },
        ),
        migrations.CreateModel(
            name='MedicalTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.CharField(choices=[('', '----------'), ('AMN', 'Amniocentesis'), ('BA', 'Blood Analysis'), ('GFA', 'Gastric Fluid Analysis'), ('KFT', 'Kidney Function Test'), ('LFT', 'Liver Function Test'), ('LP', 'Lumbar Puncture'), ('MT', 'Malabsorption Test'), ('PS', 'PAP Smear'), ('PHT', 'Phenolsulfonphthalein Test'), ('PGT', 'Pregnancy Test'), ('PNT', 'Prenatal Test'), ('PBIO', 'Protein-Bound Iodine Test'), ('SYPT', 'Syphilis Test'), ('THOR', 'Thoracentesis'), ('TFT', 'Thyroid Function Test'), ('TXT', 'Toxicology Test'), ('UR', 'Urinalysis/Uroscopy'), ('DI', 'Diagnostic Imaging'), ('GT', 'Genetic Testing'), ('M', 'Measurement'), ('PAVE', 'Physical and Visual Examination')], help_text='Medical Test Type', max_length=100, null=True, verbose_name='Test Type')),
                ('name', models.CharField(help_text='Medical Test Name', max_length=150, null=True, verbose_name='Test Name')),
                ('created_by', models.ForeignKey(blank=True, help_text='Created By', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medical_test', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Medical Test',
                'verbose_name_plural': 'Medical Tests',
                'ordering': ('name',),
                'unique_together': {('test_type', 'name', 'created_by')},
            },
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='drugs name', max_length=200, null=True, verbose_name='drug')),
                ('category', models.CharField(choices=[('AP', 'Antipyretics'), ('AG', 'Analgesics'), ('AM', 'Antimalarial'), ('AB', 'Antibiotics'), ('AS', 'Antiseptics'), ('MS', 'Mood Stabilizers'), ('HR', 'Hormone Replacement'), ('OC', 'Oral Contraceptives'), ('S', 'Stimulants'), ('T', 'Tranquilizers'), ('ST', 'Statins')], help_text='Category', max_length=50, null=True, verbose_name='category')),
                ('created_by', models.ForeignKey(blank=True, help_text='Drug created by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drug', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Drug',
                'verbose_name_plural': 'Drugs',
                'unique_together': {('name', 'created_by')},
            },
        ),
        migrations.AddField(
            model_name='baseconsult',
            name='drugs',
            field=models.ManyToManyField(blank=True, help_text='Drugs recommended', to='appointments.Drug', verbose_name='Drugs'),
        ),
        migrations.AddField(
            model_name='baseconsult',
            name='icd_10_group',
            field=models.ForeignKey(blank=True, help_text='ICD-10 group for the diagnose', null=True, on_delete=django.db.models.deletion.CASCADE, to='appointments.icd10group', verbose_name='ICD-10 Group'),
        ),
        migrations.AddField(
            model_name='baseconsult',
            name='patient',
            field=models.ForeignKey(help_text='Patient assisting this consult', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consult', to='patients.patient', verbose_name='Patient'),
        ),
        migrations.AddField(
            model_name='baseconsult',
            name='testing',
            field=models.ManyToManyField(blank=True, help_text='Pending Testing', to='appointments.MedicalTest', verbose_name='Testing'),
        ),
        migrations.AlterUniqueTogether(
            name='baseconsult',
            unique_together={('created_by', 'datetime')},
        ),
    ]
